source "https://rubygems.org"
ruby ">= 3.1"

gem "rails",            "~> 8.0"
gem "sqlite3",          ">= 2.1"
gem "puma",             ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "propshaft"
gem "tailwindcss-rails"
gem "jbuilder"

group :development, :test do
  gem "debug", platforms: %i[mri windows linux]
end

group :development do
  gem "web-console"
end
